-- ═══════════════════════════════════════════════════════
-- Admin Setup Seed (run once after D1 schema init)
--
-- IMPORTANT: Replace the password_hash and totp_secret
-- with values generated by the /api/auth/setup endpoint.
-- This file is a TEMPLATE only.
-- ═══════════════════════════════════════════════════════

-- Placeholder admin (DO NOT use in production — use /api/auth/setup instead)
-- The setup endpoint will hash the password and generate a real TOTP secret.
INSERT OR IGNORE INTO admin_users (user_id, email, password_hash, totp_secret, name)
VALUES (
  'admin_daniil',
  'dosipov@gmu.edu',
  'PLACEHOLDER_USE_SETUP_ENDPOINT',
  'PLACEHOLDER_USE_SETUP_ENDPOINT',
  'Daniil Osipov'
);
